name: Pages

on:
  push:
    branches:
      - main

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: disable workflow commands
        run: |
          echo '::warning:: this is a warning'
          echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"
          echo '::warning:: this will NOT be a warning'
          echo "::`ls`"
          echo '::warning:: this is a warning again'
            - name: manifest Version
      - name: qiniu access
        uses: deef0000dragon1/json-edit-action/@v1
        env:
          KEY: access_key
          VALUE:  ${{ secrets.QINIU_ACCESS_KEY }}
          FILE: qiniu.json
      # - name: qiniu access
      #   uses: MerthinTechnologies/edit-json-action@v1
      #   with:
      #     filename: './qiniu.json'
      #     key: 'access_key'
      #     value: ${{ secrets.QINIU_ACCESS_KEY }}
      # - name: qiniu secret
      #   uses: MerthinTechnologies/edit-json-action@v1
      #   with:
      #     filename: './qiniu.json'
      #     key: 'secret_key'
      #     value: ${{ secrets.QINIU_SECRET_KEY }}
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages